# Sentiment Analysis of Tech Company Tweets

In [1]:
# importing libraries
import os
import pandas as pd

In [2]:
# reading in data
Tweet = pd.read_csv("Tweet.csv")
Tweet.head()

,tweet_id,writer,post_date,body,comment_num,retweet_num,like_num,ticker_symbol,company,engagement,date
0,5.504415e+17,VisualStockRSRC,1420070457,"lx21 made $10,008 on $AAPL -Check it out! htt...",0,0,1,AAPL,Apple,1,2015-01-01
1,5.504417e+17,KeralaGuy77,1420070496,Insanity of today weirdo massive selling. $aap...,0,0,0,AAPL,Apple,0,2015-01-01
2,5.504417e+17,DozenStocks,1420070510,S&P100 #Stocks Performance $HD $LOW $SBUX $TGT...,0,0,0,AMZN,Amazon,0,2015-01-01
3,5.504430e+17,ShowDreamCar,1420070807,$GM $TSLA: Volkswagen Pushes 2014 Record Recal...,0,0,1,TSLA,Tesla,1,2015-01-01
4,5.504438e+17,i_Know_First,1420071005,Swing Trading: Up To 8.91% Return In 14 Days h...,0,0,1,AAPL,Apple,1,2015-01-01

In [4]:
# importing the VADER sentiment analyzer
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
analyzer = SentimentIntensityAnalyzer()

In [5]:
# filtering out tweets with engagement less than 5 
Tweet2 = Tweet[Tweet['engagement']>=5]
# cleaning tweet body 
Tweet2['prep_body'] = Tweet2['body'].replace(r"https?:\S+|http?:\S+|www?:\S+", '', regex=True).replace(r"[@#\$][a-zA-Z]+", '', regex=True).replace(r"\s\s+", ' ', regex=True).str.strip()

<ipython-input-5-bfeb9d7ba824>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Tweet2['prep_body'] = Tweet2['body'].replace(r"https?:\S+|http?:\S+|www?:\S+", '', regex=True).replace(r"[@#\$][a-zA-Z]+", '', regex=True).replace(r"\s\s+", ' ', regex=True).str.strip()

In [6]:
# calculating sentiment scores

compound=[]
positive=[]
negative=[]

for i in range(0, len(Tweet2)):
    compound.append(analyzer.polarity_scores(Tweet2.iloc[i]['prep_body'])['compound'])
    positive.append(analyzer.polarity_scores(Tweet2.iloc[i]['prep_body'])['pos'])
    negative.append(analyzer.polarity_scores(Tweet2.iloc[i]['prep_body'])['neg'])

In [7]:
Tweet2['compound']=compound
Tweet2['positive']=positive
Tweet2['negative']=negative
Tweet2.head()

<ipython-input-7-10a74e9e69be>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Tweet2['compound']=compound
<ipython-input-7-10a74e9e69be>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Tweet2['positive']=positive
<ipython-input-7-10a74e9e69be>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Tweet2['negative']=negative

,tweet_id,writer,post_date,body,comment_num,retweet_num,like_num,ticker_symbol,company,engagement,date,compound,prep_body,positive,negative
33,5.504531e+17,DCaptura,1420073217,"""http://iphone.appleinsider.com/articles/14/12...",0,3,3,AAPL,Apple,6,2015-01-01,0.6249,""" . Awesome journalism as usual.",0.451,0.000
35,5.504536e+17,WSJ,1420073345,Jeff Bezos lost $7.4 billion in Amazon's worst...,21,139,57,AMZN,Amazon,217,2015-01-01,-0.7506,Jeff Bezos lost $7.4 billion in Amazon's worst...,0.000,0.416
103,5.504798e+17,themotleyfool,1420079580,"#FoolFaves2014 Lo, how the mighty have fallen?...",0,7,5,AAPL,Apple,12,2015-01-01,-0.3612,"2014 Lo, how the mighty have fallen? Why the f...",0.000,0.143
110,5.504891e+17,CNBC,1420081814,"Earlier this month, a mysterious glitch caused...",4,18,17,AAPL,Apple,39,2015-01-01,-0.2732,"Earlier this month, a mysterious glitch caused...",0.000,0.139
121,5.504992e+17,WSJ,1420084206,Jeff Bezos lost $7.4 billion in Amazon's worst...,17,113,57,AMZN,Amazon,187,2015-01-01,-0.7506,Jeff Bezos lost $7.4 billion in Amazon's worst...,0.000,0.416

In [9]:
Tweet2.to_csv('SentimentTweet2.csv')

In [10]:
# repeating with full dataset

# clean
Tweet['prep_body'] = Tweet['body'].replace(r"https?:\S+|http?:\S+|www?:\S+", '', regex=True).replace(r"[@#\$][a-zA-Z]+", '', regex=True).replace(r"\s\s+", ' ', regex=True).str.strip()

In [11]:
Tweet.head()['prep_body']

0            lx21 made $10,008 on -Check it out! Learn
1    Insanity of today weirdo massive selling. bid ...
2                             S&P100 Performance more@
3    : Volkswagen Pushes 2014 Record Recall Tally H...
4         Swing Trading: Up To 8.91% Return In 14 Days
Name: prep_body, dtype: object

In [13]:
# calculating sentiment scores

compound_full=[]
positive_full=[]
negative_full=[]

for i in range(0, len(Tweet)):
    compound_full.append(analyzer.polarity_scores(Tweet.iloc[i]['prep_body'])['compound'])
    positive_full.append(analyzer.polarity_scores(Tweet.iloc[i]['prep_body'])['pos'])
    negative_full.append(analyzer.polarity_scores(Tweet.iloc[i]['prep_body'])['neg'])

In [14]:
Tweet['compound']=compound_full
Tweet['positive']=positive_full
Tweet['negative']=negative_full
Tweet2.head()

,tweet_id,writer,post_date,body,comment_num,retweet_num,like_num,ticker_symbol,company,engagement,date,compound,prep_body,positive,negative
33,5.504531e+17,DCaptura,1420073217,"""http://iphone.appleinsider.com/articles/14/12...",0,3,3,AAPL,Apple,6,2015-01-01,0.6249,""" . Awesome journalism as usual.",0.451,0.000
35,5.504536e+17,WSJ,1420073345,Jeff Bezos lost $7.4 billion in Amazon's worst...,21,139,57,AMZN,Amazon,217,2015-01-01,-0.7506,Jeff Bezos lost $7.4 billion in Amazon's worst...,0.000,0.416
103,5.504798e+17,themotleyfool,1420079580,"#FoolFaves2014 Lo, how the mighty have fallen?...",0,7,5,AAPL,Apple,12,2015-01-01,-0.3612,"2014 Lo, how the mighty have fallen? Why the f...",0.000,0.143
110,5.504891e+17,CNBC,1420081814,"Earlier this month, a mysterious glitch caused...",4,18,17,AAPL,Apple,39,2015-01-01,-0.2732,"Earlier this month, a mysterious glitch caused...",0.000,0.139
121,5.504992e+17,WSJ,1420084206,Jeff Bezos lost $7.4 billion in Amazon's worst...,17,113,57,AMZN,Amazon,187,2015-01-01,-0.7506,Jeff Bezos lost $7.4 billion in Amazon's worst...,0.000,0.416

In [18]:
Tweet3 = Tweet[['tweet_id','post_date','body','ticker_symbol','company','engagement', 'date','compound']]

In [19]:
Tweet3.to_csv('SentimentFull.csv')

### Some fun questions to explore
* What time are people tweeting the most? Is there a relationship between tweet sentiment & time?